#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jun 30 08:36:17 IST 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim axi_vip_tb_behav -key {Behavioral:sim_1:Functional:axi_vip_tb} -tclbatch axi_vip_tb.tcl -protoinst "protoinst_files/vip_bd.protoinst" -log simulate.log"
xsim axi_vip_tb_behav -key {Behavioral:sim_1:Functional:axi_vip_tb} -tclbatch axi_vip_tb.tcl -protoinst "protoinst_files/vip_bd.protoinst" -log simulate.log

